=== txominpelu/dynamicrefactoring.plugin/dynamicrefactoring.tests/testdata/XML/Reader/refactoringPlan/refactoringPlanDTD.dtd
<!ELEMENT RefactoringPlan ( refactoring* ) >

<!ELEMENT refactoring (name, date, parameters)  >

<!ELEMENT name EMPTY >
<!ATTLIST name value CDATA #REQUIRED >

<!ELEMENT date EMPTY >
<!ATTLIST date value CDATA #REQUIRED >

<!ELEMENT parameters ( parameter* ) >

<!ELEMENT parameter EMPTY >
<!ATTLIST parameter name CDATA #REQUIRED >
<!ATTLIST parameter value CDATA #REQUIRED >
<!ATTLIST parameter isName (false|true) #IMPLIED >

=== txominpelu/dynamicrefactoring.plugin/dynamicrefactoring.tests/testdata/XML/Reader/refactoringPlan/completeRefactoringPlan.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE RefactoringPlan SYSTEM "refactoringPlanDTD.dtd">

<RefactoringPlan>
	<refactoring>
		<name value="Add Parameter" />
		<date value="02/20/09 - 12:42:34" />
		<parameters>
			<parameter name="Name" value="p4" />
			<parameter name="Method" value="paqueteA.C~met1%int%Double%short" />
			<parameter name="Type" value="int" />
			<parameter name="Class" value="paqueteA.C" />
		</parameters>
	</refactoring>
	<refactoring>
		<name value="Move Field" />
		<date value="02/20/09 - 12:43:26" />
		<parameters>
			<parameter name="Source_class" value="paqueteA.H" />
			<parameter name="Attribute" value="paqueteA.H#atributo1" />
			<parameter name="Target_class" value="paqueteA.B" />
		</parameters>
	</refactoring>
	<refactoring>
		<name value="ExtractMethod" />
		<date value="02/20/09 - 12:44:58" />
		<parameters>
			<parameter name="Name" value="nuevo_metodo" />
			<parameter name="Fragment" value="11,8,11,29,paqueteA.E,System.out.println(a);" />
		</parameters>
	</refactoring>
</RefactoringPlan>
