=== txominpelu/dynamicrefactoring.plugin/dynamicrefactoring.tests/testdata/XML/Reader/availableRefactorings/refactoringsDTD.dtd
<!ELEMENT dynamicRefactorings ( classdef, methdec, attdec, formalArgument, formalPar, codeFragment ) >

<!ELEMENT classdef ( refactoring* ) >


<!ELEMENT methdec ( refactoring* ) >

<!ELEMENT attdec ( refactoring* ) >
<!ELEMENT formalArgument ( refactoring* ) >
<!ELEMENT formalPar ( refactoring* ) >
<!ELEMENT codeFragment ( refactoring* ) >

<!ELEMENT refactoring EMPTY >
<!ATTLIST refactoring name CDATA #REQUIRED >
<!ATTLIST refactoring path CDATA #REQUIRED >

=== txominpelu/dynamicrefactoring.plugin/refactorings.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE dynamicRefactorings SYSTEM "refactoringsDTD.dtd">

<dynamicRefactorings>
	<classdef>
		<refactoring name="EnumeratedTypes" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/EnumeratedTypes/EnumeratedTypes.xml" />
		<refactoring name="MigrateJUnit3ToJUnit4" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/MigrateJUnit3ToJUnit4/MigrateJUnit3ToJUnit4.xml" />
		<refactoring name="Rename Class" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Rename Class/Rename Class.xml" />
	</classdef>
	<methdec>
		<refactoring name="MigrateJUnit3ToJUni4TestException" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/MigrateJUnit3ToJUni4TestException/MigrateJUnit3ToJUni4TestException.xml" />
		<refactoring name="Rename Method" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Rename Method/Rename Method.xml" />
		<refactoring name="Add Parameter" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Add Parameter/Add Parameter.xml" />
		<refactoring name="AddOverrideAnnotation" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/AddOverrideAnnotation/AddOverrideAnnotation.xml" />
	</methdec>
	<attdec>
		<refactoring name="Tal" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Tal/Tal.xml" />
		<refactoring name="Rename Field" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Rename Field/Rename Field.xml" />
		<refactoring name="Move Field" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Move Field/Move Field.xml" />
	</attdec>
	<formalArgument>
		<refactoring name="Rename Parameter" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Rename Parameter/Rename Parameter.xml" />
		<refactoring name="Remove Parameter" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Remove Parameter/Remove Parameter.xml" />
	</formalArgument>
	<formalPar>
		<refactoring name="Specialize Bound S" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Specialize Bound S/Specialize Bound S.xml" />
		<refactoring name="Replace Formal Parameter With Type" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Replace Formal Parameter With Type/Replace Formal Parameter With Type.xml" />
		<refactoring name="Replace Formal Parameter With Bounding Type" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/Replace Formal Parameter With Bounding Type/Replace Formal Parameter With Bounding Type.xml" />
	</formalPar>
	<codeFragment>
		<refactoring name="ExtractMethod" path="/home/imediava/Escritorio/Proyecto/CodigoFuente/2.0.0 Dynamic refactoring/DynamicRefactorings/ExtractMethod/ExtractMethod.xml" />
	</codeFragment>
</dynamicRefactorings>

=== txominpelu/dynamicrefactoring.plugin/dynamicrefactoring.tests/testdata/XML/Reader/availableRefactorings/incompleteInformation.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE dynamicRefactorings SYSTEM "refactoringsDTD.dtd">

<dynamicRefactorings>
	<classdef>
		<refactoring name="EnumeratedTypes" path="..\Documents and Settings\Laura\workspace\2.0.12 Dynamic refactoring\DynamicRefactorings\EnumeratedTypes\EnumeratedTypes.xml" />
	</classdef>
	<methdec>
		<refactoring name="MigrateJUnit3ToJUni4TestException" path="..\Documents and Settings\Laura\workspace\2.0.12 Dynamic refactoring\DynamicRefactorings\MigrateJUnit3ToJUni4TestException\MigrateJUnit3ToJUni4TestException.xml" />
		<refactoring name="Rename Method" path="..\Documents and Settings\Laura\workspace\2.0.12 Dynamic refactoring\DynamicRefactorings\Rename Method\Rename Method.xml" />
	</methdec>
	<formalArgument>
		<refactoring name="Rename Parameter" path="..\Documents and Settings\Laura\workspace\2.0.12 Dynamic refactoring\DynamicRefactorings\Rename Parameter\Rename Parameter.xml" />
	</formalArgument>
	<formalPar>
		<refactoring name="Specialize Bound S" path="..\Documents and Settings\Laura\workspace\2.0.12 Dynamic refactoring\DynamicRefactorings\Specialize Bound S\Specialize Bound S.xml" />
	</formalPar>
</dynamicRefactorings>

=== txominpelu/dynamicrefactoring.plugin/dynamicrefactoring.tests/testdata/XML/Reader/availableRefactorings/completedInformation.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE dynamicRefactorings SYSTEM "refactoringsDTD.dtd">

<dynamicRefactorings>
	<classdef>
		<refactoring name="EnumeratedTypes" path=".\DynamicRefactorings\EnumeratedTypes\EnumeratedTypes.xml" />
		<refactoring name="MigrateJUnit3ToJUnit4" path=".\DynamicRefactorings\MigrateJUnit3ToJUnit4\MigrateJUnit3ToJUnit4.xml" />
		<refactoring name="Rename Class" path=".\DynamicRefactorings\Rename Class\Rename Class.xml" />
	</classdef>
	<methdec>
		<refactoring name="MigrateJUnit3ToJUni4TestException" path=".\DynamicRefactorings\MigrateJUnit3ToJUni4TestException\MigrateJUnit3ToJUni4TestException.xml" />
		<refactoring name="Rename Method" path=".\DynamicRefactorings\Rename Method\Rename Method.xml" />
		<refactoring name="Add Parameter" path=".\DynamicRefactorings\Add Parameter\Add Parameter.xml" />
		<refactoring name="AddOverrideAnnotation" path=".\DynamicRefactorings\AddOverrideAnnotation\AddOverrideAnnotation.xml" />
	</methdec>
	<attdec>
		<refactoring name="Move Field" path=".\DynamicRefactorings\Move Field\Move Field.xml" />
	</attdec>
	<formalArgument>
		<refactoring name="Rename Parameter" path=".\DynamicRefactorings\Rename Parameter\Rename Parameter.xml" />
		<refactoring name="Remove Parameter" path=".\DynamicRefactorings\Remove Parameter\Remove Parameter.xml" />
	</formalArgument>
	<formalPar>
		<refactoring name="Specialize Bound S" path=".\DynamicRefactorings\Specialize Bound S\Specialize Bound S.xml" />
		<refactoring name="Replace Formal Parameter With Type" path=".\DynamicRefactorings\Replace Formal Parameter With Type\Replace Formal Parameter With Type.xml" />
		<refactoring name="Replace Formal Parameter With Bounding Type" path=".\DynamicRefactorings\Replace Formal Parameter With Bounding Type\Replace Formal Parameter With Bounding Type.xml" />
	</formalPar>
	<codeFragment>
		<refactoring name="ExtractMethod" path=".\DynamicRefactorings\ExtractMethod\ExtractMethod.xml" />
	</codeFragment>
</dynamicRefactorings>
